### ISSUE TITLE
Custom css animations/transitions support

### ISSUE THREAD

**Issue by wclr** [bitovi/can-animate#1]
Have you thought about this?

**Comment by justinbmeyer** [comment]
What do you mean?  It supports custom animation values.

**Comment by wclr** [comment]
If I want to configure animation via css?

**Comment by wclr** [comment]
So the flow in this case would be:

Insertion:
1) When element is just inserted in DOM it gets some class `animate-in` (css animation is performed)
2) Waites animation/transition end, removes this class

Removal:
1) When element is going to be removed from DOM it gets some class `animate-out` (css animation is performed)
2) Waites animation/transition end, removes element from DOM.

**Comment by justinbmeyer** [comment]
@whitecolor Have you read the docs on this?  For example: https://github.com/bitovi/can-animate/blob/master/doc/when.md or https://github.com/bitovi/can-animate/blob/master/doc/style.md#use

You can achive pretty close to what you are asking.  I'm not sure if we can do it via className (not all browsers support CSS animations).  However something like:

```
<div can-animate-when="inserted" can-animate-style="opacity: 1" style="opacity: 0">
```

**Comment by justinbmeyer** [comment]
cc @jandjorgensen

**Comment by wclr** [comment]
> I'm not sure if we can do it via className (not all browsers support CSS animations)

why care too badly about old browsers, anyway all mordern browsers and even all mobile do support css animations (in some way) it would be responsobility of applicaiton dev

**Comment by wclr** [comment]
@justinbmeyer this actually pretty easy to implement, it would be also good to have before remove hooks API (so one could define what will happen when element is going to be removed).

**Comment by whitecolor** [comment]
Why this code doesn't work?

```javascript
var oldRemove = can.remove;

can.remove = function (wrapped) {
    return oldRemove.apply(this, arguments);
};
```

the error:
```
 Potentially unhandled rejection [1] TypeError: Cannot read property 'attributes' of undefined
    at addAttributesCallback (http://bbooks-reader.local:7001/bower_components/canjs/view/stache/stache.js:100:14)
    at Object.parser.close (http://bbooks-reader.local:7001/bower_components/canjs/view/stache/stache.js:154:6)
    at parseEndTag (http://bbooks-reader.local:7001/bower_components/canjs/view/parser/parser.js:115:15)
    at String.replace (native)
    at HTMLParser (http://bbooks-reader.local:7001/bower_components/canjs/view/parser/parser.js:160:16)
    at stache (http://bbooks-reader.local:7001/bower_components/canjs/view/stache/stache.js:106:3)
    at Object.can.view.register.fragRenderer (http://bbooks-reader.local:7001/bower_components/canjs/view/stache/stache.js:312:11)
    at Function.can.extend.register.can.(anonymous function).$view.(anonymous function).renderFunc (http://bbooks-reader.local:7001/bower_components/canjs/view/view.js:404:25)
    at Constructor.can.Component.can.Construct.extend.setup (http://bbooks-reader.local:7001/bower_components/canjs/component/component.js:300:30)
    at Function.can.extend.newInstance (http://bbooks-reader.local:7001/bower_components/canjs/construct/construct.js:114:23)
```

**Comment by justinbmeyer** [comment]
I think jan got remove working
